version: "3"
services:
  server:
    image: local/toxic-cards
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      IO_PORT: 80
