services:
  server:
    image: lekato/toxic-cards
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    volumes:
#      - ./build:/app/build
#      - ./node_modules:/app/node_modules
    environment:
      PORT: 3000
      NODE_ENV: production
